"""criação inicial: users e work_records

Revision ID: 28abd5d14336
Revises: 
Create Date: 2026-09-22 00:12:03.019826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28abd5d14336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('work_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('costs IS NULL OR costs >= 0', name='ck_costs_non_negative'),
    sa.CheckConstraint('earnings IS NULL OR earnings >= 0', name='ck_earnings_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_open_shift_per_user', ['user_id'], unique=True, postgresql_where=sa.text('end_time IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.drop_index('ux_open_shift_per_user', postgresql_where=sa.text('end_time IS NULL'))
        batch_op.drop_index(batch_op.f('ix_work_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_records_date'))

    op.drop_table('work_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
